#!/bin/bash
set -e

# {{ cookiecutter.project_name }} - Development Stop Script
# Generated by Lich Cookiecutter Framework

echo "🛑 Stopping {{ cookiecutter.project_name }} Development Environment"
echo "======================================================================"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Stop PID-based services
if [ -d ".pids" ]; then
    for pid_file in .pids/*.pid; do
        if [ -f "$pid_file" ]; then
            pid=$(cat "$pid_file")
            service=$(basename "$pid_file" .pid)
            if kill -0 "$pid" 2>/dev/null; then
                echo "Stopping $service (PID: $pid)..."
                kill "$pid" 2>/dev/null || true
            fi
            rm "$pid_file"
        fi
    done
fi

# Kill remaining processes on ports
echo -e "\n${YELLOW}Cleaning up ports...${NC}"
for port in 8000 3000 3002 4321; do
    pids=$(lsof -ti :$port 2>/dev/null || true)
    if [ -n "$pids" ]; then
        echo "  Freeing port $port..."
        echo "$pids" | xargs kill -9 2>/dev/null || true
    fi
done

# Optionally stop Docker
echo ""
read -p "Stop Docker services? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Stopping Docker services..."
    docker-compose down
fi

echo -e "\n${GREEN}✅ All services stopped!${NC}"
