#!/bin/bash
set -e

# {{ cookiecutter.project_name }} - Development Start Script
# Generated by Lich Cookiecutter Framework

echo "🚀 Starting {{ cookiecutter.project_name }} Development Environment"
echo "======================================================================"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Create directories
mkdir -p .pids .logs

# Check Docker
if ! docker info > /dev/null 2>&1; then
    echo -e "${RED}❌ Docker is not running! Please start Docker first.${NC}"
    exit 1
fi

# Check ports function
check_port() {
    if lsof -Pi :$1 -sTCP:LISTEN -t >/dev/null 2>&1; then
        echo -e "${YELLOW}⚠️  Port $1 is in use. Kill process? (y/n)${NC}"
        read -r answer
        if [ "$answer" = "y" ]; then
            lsof -ti :$1 | xargs kill -9 2>/dev/null || true
            echo -e "${GREEN}✅ Port $1 freed${NC}"
        else
            echo -e "${RED}❌ Cannot continue with port $1 in use${NC}"
            exit 1
        fi
    fi
}

# Check required ports
echo -e "\n${GREEN}🔍 Checking ports...${NC}"
check_port 8000  # Backend API
check_port 3000  # Web App
check_port 3002  # Admin Panel
check_port 4321  # Landing Page

# Start Docker services
echo -e "\n${GREEN}📦 Starting Docker services...${NC}"
{%- if cookiecutter.auth_strategy == 'keycloak' %}
docker-compose up -d {% if cookiecutter.database == 'postgresql' %}postgres{% else %}mongodb{% endif %} {% if cookiecutter.use_redis == 'yes' %}redis{% endif %} keycloak adminer 2>/dev/null || \
docker-compose up -d {% if cookiecutter.database == 'postgresql' %}postgres{% else %}mongodb{% endif %} {% if cookiecutter.use_redis == 'yes' %}redis{% endif %} adminer
{%- else %}
docker-compose up -d {% if cookiecutter.database == 'postgresql' %}postgres{% else %}mongodb{% endif %} {% if cookiecutter.use_redis == 'yes' %}redis{% endif %} adminer
{%- endif %}

# Wait for database
echo "⏳ Waiting for database..."
{%- if cookiecutter.database == 'postgresql' %}
until docker-compose exec -T postgres pg_isready -U app > /dev/null 2>&1; do
    sleep 1
done
{%- else %}
sleep 5  # MongoDB takes a moment
{%- endif %}
echo -e "${GREEN}✅ Database ready${NC}"

# Start Backend
echo -e "\n${GREEN}🐍 Starting Backend...${NC}"
cd backend
if [ ! -d "venv" ]; then
    echo "   Creating virtual environment..."
    python3 -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt -q
else
    source venv/bin/activate
fi

# Copy .env if not exists
if [ ! -f ".env" ]; then
    cp .env.example .env 2>/dev/null || echo "   No .env.example found"
fi

nohup python main.py > ../.logs/backend.log 2>&1 &
echo $! > ../.pids/backend.pid
cd ..

# Wait for Backend
echo "⏳ Waiting for Backend API..."
for i in {1..30}; do
    if curl -s http://localhost:8000/health > /dev/null 2>&1; then
        echo -e "${GREEN}✅ Backend ready${NC}"
        break
    fi
    sleep 1
done

# Start Web App
echo -e "\n${GREEN}⚛️  Starting Web App...${NC}"
cd apps/web
if [ ! -d "node_modules" ]; then
    echo "   Installing dependencies..."
    npm install --silent
fi
nohup npm run dev > ../../.logs/web.log 2>&1 &
echo $! > ../../.pids/web.pid
cd ../..

# Start Admin Panel
echo -e "\n${GREEN}👤 Starting Admin Panel...${NC}"
cd apps/admin
if [ ! -d "node_modules" ]; then
    echo "   Installing dependencies..."
    npm install --silent
fi
nohup npm run dev > ../../.logs/admin.log 2>&1 &
echo $! > ../../.pids/admin.pid
cd ../..

# Start Landing Page
echo -e "\n${GREEN}🌐 Starting Landing Page...${NC}"
cd apps/landing
if [ ! -d "node_modules" ]; then
    echo "   Installing dependencies..."
    npm install --silent
fi
nohup npm run dev > ../../.logs/landing.log 2>&1 &
echo $! > ../../.pids/landing.pid
cd ../..

# Wait for frontend
echo "⏳ Waiting for frontends to start..."
sleep 5

# Summary
echo -e "\n${GREEN}======================================================================"
echo "✅ All services started!"
echo "======================================================================${NC}"
echo ""
echo "🔗 Service URLs:"
echo "   • Web App:      http://localhost:3000"
echo "   • Admin Panel:  http://localhost:3002"
echo "   • Landing Page: http://localhost:4321"
echo "   • API Docs:     http://localhost:8000/api/docs"
{%- if cookiecutter.auth_strategy == 'keycloak' %}
echo "   • Keycloak:     http://localhost:8080"
{%- endif %}
echo "   • Adminer:      http://localhost:8091"
{%- if cookiecutter.use_temporal == 'yes' %}
echo "   • Temporal UI:  http://localhost:8088"
{%- endif %}
{%- if cookiecutter.landing_backend == 'wordpress_api' %}
echo "   • WordPress:    http://localhost:8081"
{%- endif %}
echo ""
echo "📁 Logs:     .logs/"
echo "🛑 Stop:     ./dev-stop.sh"
