"""
Cookiecutter Post-Generation Hook.
Cleans up files based on user choices and shows service URLs.
"""
import os
import shutil


def remove_file(filepath):
    """Remove a file if it exists."""
    if os.path.exists(filepath):
        os.remove(filepath)
        print(f"  Removed: {filepath}")


def remove_dir(dirpath):
    """Remove a directory if it exists."""
    if os.path.exists(dirpath):
        shutil.rmtree(dirpath)
        print(f"  Removed: {dirpath}")


def make_executable(filepath):
    """Make a file executable."""
    if os.path.exists(filepath):
        os.chmod(filepath, 0o755)


def main():
    """Clean up based on cookiecutter choices."""
    print("\n🧹 Cleaning up based on your choices...")
    
    project_dir = os.getcwd()
    
    {%- if cookiecutter.auth_strategy != 'keycloak' %}
    remove_file(os.path.join(project_dir, "scripts", "setup-keycloak.sh"))
    {%- endif %}
    
    # Make scripts executable
    scripts = [
        "dev-start.sh",
        "dev-stop.sh",
        "scripts/validate-env.sh",
    ]
    {%- if cookiecutter.auth_strategy == 'keycloak' %}
    scripts.append("scripts/setup-keycloak.sh")
    {%- endif %}
    
    for script in scripts:
        make_executable(os.path.join(project_dir, script))
    
    # Initialize git repository
    os.system("git init -q 2>/dev/null || true")
    
    print("\n✅ Project setup complete!")
    print("\n" + "="*50)
    print("📚 {{ cookiecutter.project_name }}")
    print("="*50)
    
    print("\n📋 QUICK START:")
    print("   1. cd {{ cookiecutter.project_slug }}")
    print("   2. cp .env.example .env")
    print("   3. ./dev-start.sh")
    
    print("\n🌐 SERVICE URLS:")
    print("-"*50)
    print("   Web App:        http://localhost:3000")
    print("   Admin Panel:    http://localhost:3002")
    print("   Landing Page:   http://localhost:4321")
    print("   API Docs:       http://localhost:8000/api/docs")
    print("-"*50)
    
    print("\n🔧 INFRASTRUCTURE:")
    print("-"*50)
    print("   Traefik:        http://localhost:8090")
    {%- if cookiecutter.database == 'postgresql' %}
    print("   PostgreSQL:     localhost:5432")
    {%- else %}
    print("   MongoDB:        localhost:27017")
    {%- endif %}
    {%- if cookiecutter.use_redis == 'yes' %}
    print("   Redis:          localhost:6379")
    {%- endif %}
    print("   Adminer:        http://localhost:8091")
    {%- if cookiecutter.auth_strategy == 'keycloak' %}
    print("   Keycloak:       http://localhost:8080")
    {%- endif %}
    {%- if cookiecutter.use_temporal == 'yes' %}
    print("   Temporal UI:    http://localhost:8088")
    {%- endif %}
    {%- if cookiecutter.landing_backend == 'wordpress_api' %}
    print("   WordPress:      http://localhost:8081")
    {%- endif %}
    print("-"*50)
    
    {%- if cookiecutter.use_tls == 'yes' %}
    print("\n🔒 TLS ENABLED:")
    print("   Domain: {{ cookiecutter.domain_name }}")
    print("   Certificates will be auto-generated by Let's Encrypt")
    {%- endif %}
    
    print("\n📄 See QUICK_START.md for detailed documentation")
    print("="*50 + "\n")


if __name__ == "__main__":
    main()
